base:
  project: winequality-project
  random_state: 42
  target_col: TARGET

data_source:
  s3_source: data_given/winequality-white.csv

load_data:
  raw_data_csv: data/raw/winequality-white.csv

split_data:
  train_path: data/processed/train_winequality-white.csv
  test_path: data/processed/test_winequality-white.csv
  test_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
model_dir: saved_models